services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bus_booking
    container_name: 'postgresql-container-bus-booking'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    restart: always
